services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
            - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
        working_dir: /var/www/html
        ports:
            - 8080:80
        networks:
            - laravel
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel_db
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

    composer:
        image: composer:latest
        container_name: laravel_composer
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: ["composer"]

    swagger:
        image: swaggerapi/swagger-ui:latest
        container_name: swagger_ui
        ports:
            - 8081:8080
        environment:
            SWAGGER_JSON: /swagger/api-docs.json
        volumes:
            - ./swagger:/swagger
        networks:
            - laravel

networks:
    laravel:

volumes:
    db_data:
